In [1]:
import torch

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5

x = torch.randn(3, 4, 5)
x, x.type()

(tensor([[[-0.8380,  0.4305, -0.1239, -0.7449, -0.5318],
          [ 0.8528, -0.2518,  0.0977,  0.5378, -0.9731],
          [ 0.5684,  0.1301, -1.1808,  0.5905, -0.5835],
          [ 0.2277, -1.4556,  1.7186,  0.3101, -0.7552]],
 
         [[-0.0479, -0.8007,  1.2252,  0.9343,  1.2153],
          [-0.6835, -3.2434,  0.3007,  2.2330, -0.7055],
          [-0.5312,  1.4174, -0.9492,  1.3799, -0.6286],
          [-0.0507,  2.4636,  1.5657, -1.2518, -0.0035]],
 
         [[-0.1966, -0.7796, -0.4625, -2.2089,  1.1863],
          [ 0.5667, -0.9487, -1.4990,  0.6289, -1.5619],
          [-1.3476,  0.7282, -0.8810,  0.0706,  0.8841],
          [-1.1705,  0.5235, -1.5248, -0.6589,  1.2575]]]),
 'torch.FloatTensor')

In [3]:
# 2. Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [4]:
# 3. Приведите его к форме 6х10
x = x.reshape(6, 10)
x

tensor([[-0.8380,  0.4305, -0.1239, -0.7449, -0.5318,  0.8528, -0.2518,  0.0977,
          0.5378, -0.9731],
        [ 0.5684,  0.1301, -1.1808,  0.5905, -0.5835,  0.2277, -1.4556,  1.7186,
          0.3101, -0.7552],
        [-0.0479, -0.8007,  1.2252,  0.9343,  1.2153, -0.6835, -3.2434,  0.3007,
          2.2330, -0.7055],
        [-0.5312,  1.4174, -0.9492,  1.3799, -0.6286, -0.0507,  2.4636,  1.5657,
         -1.2518, -0.0035],
        [-0.1966, -0.7796, -0.4625, -2.2089,  1.1863,  0.5667, -0.9487, -1.4990,
          0.6289, -1.5619],
        [-1.3476,  0.7282, -0.8810,  0.0706,  0.8841, -1.1705,  0.5235, -1.5248,
         -0.6589,  1.2575]])

In [5]:
# 4. Создайте случайный IntTensor размера 10
a = torch.randint(10, size=(10,)).type(torch.IntTensor)
a, a.type()

(tensor([4, 1, 2, 5, 5, 5, 7, 7, 0, 6], dtype=torch.int32), 'torch.IntTensor')

In [6]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
xa = x * a
xa

tensor([[-3.3521e+00,  4.3048e-01, -2.4773e-01, -3.7244e+00, -2.6588e+00,
          4.2641e+00, -1.7626e+00,  6.8364e-01,  0.0000e+00, -5.8388e+00],
        [ 2.2734e+00,  1.3006e-01, -2.3616e+00,  2.9523e+00, -2.9175e+00,
          1.1386e+00, -1.0189e+01,  1.2030e+01,  0.0000e+00, -4.5314e+00],
        [-1.9152e-01, -8.0068e-01,  2.4505e+00,  4.6717e+00,  6.0766e+00,
         -3.4173e+00, -2.2703e+01,  2.1050e+00,  0.0000e+00, -4.2328e+00],
        [-2.1249e+00,  1.4174e+00, -1.8983e+00,  6.8993e+00, -3.1428e+00,
         -2.5353e-01,  1.7245e+01,  1.0960e+01, -0.0000e+00, -2.1049e-02],
        [-7.8638e-01, -7.7962e-01, -9.2491e-01, -1.1044e+01,  5.9316e+00,
          2.8337e+00, -6.6408e+00, -1.0493e+01,  0.0000e+00, -9.3716e+00],
        [-5.3902e+00,  7.2817e-01, -1.7620e+00,  3.5290e-01,  4.4207e+00,
         -5.8527e+00,  3.6642e+00, -1.0674e+01, -0.0000e+00,  7.5451e+00]])

In [7]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

xa_xa = xa @ xa.T
xa_xa

tensor([[  88.2711,   47.2789,   17.7330,  -32.9972,   99.2252,  -77.0161],
        [  47.2789,  298.3729,  261.6872,  -14.6851,  -62.4951, -226.4518],
        [  17.7330,  261.6872,  614.9072, -359.7471,  141.6217,  -92.9520],
        [ -32.9972,  -14.6851, -359.7471,  485.1937, -322.5705,  -48.0985],
        [  99.2252,  -62.4951,  141.6217, -322.5705,  409.3109,   27.9997],
        [ -77.0161, -226.4518,  -92.9520,  -48.0985,   27.9997,  270.8942]])

In [9]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x = torch.tensor([1.], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.], requires_grad=True)

y = x**3 + z - 75*t

y.backward()

print('dy/dx: ', x.grad)
print('dy/dz: ', z.grad)
print('dy/dt: ', t.grad)

dy/dx:  tensor([3.])
dy/dz:  tensor([1.])
dy/dt:  tensor([-75.])


In [10]:
# 8. Создайте единичный тензор размера 5x6

t_ones = torch.ones(5, 6)
t_ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [11]:
# 9. Переведите его в формат numpy

t_ones = t_ones.numpy()
t_ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)